### PR TITLE
Add icon and baner

### LINKED ISSUE #3: Prepare icon and banner
Prepare new logo and banner for this project.
Use QuasraApp banners style.

### PR DESCRIPTION
**Pull request by Oleg-designer**
fix #3

### CODE REVIEW

**Comment by EndrII** [comment]
Wait for merge the #2 fixes

**Comment by IgorekLoschinin** [comment]
Oleg-designer, pull the changes to the branch.

**Comment by IgorekLoschinin** [comment]
@Oleg-designer, please pull last changes into this branch.

**Review by EndrII — APPROVED** [review]
i thin its can be merged

**Pull request merged**
